---
- name: Install chrony
  dnf:
    name: chrony
    state: present

- name: Configure chrony
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    mode: '0644'
  notify: restart chronyd

- name: Enable chronyd service
  systemd:
    name: chronyd
    enabled: yes
    state: started
